### ISSUE TITLE
登录报404

### ISSUE THREAD

**Issue by kittymaxwell** [bihell/Dice#139]
## Question（提问）
你好，启动前端后，http://localhost:8011/admin/login?redirect=%2Fblog。输入用户名，密码报404.打开f12.发现Request URL: http://localhost:8011/v1/api/admin/auth/login这个报错。去后台代码搜索api/admin/auth/login，并未发现相关的login代码

**Comment by bihell** [comment]
原来的还是复杂了点，现在弄新版本打算去掉nginx这次的校验，晚点有时间更新下代码
