### ISSUE TITLE
角色管理编辑功能有点问题

### ISSUE THREAD

**Issue by xiaoboisbest** [bihell/Dice#163]
角色管理功能里，编辑权限的时候，菜单名没有显示

权限管理，新增菜单的上级菜单，也没有显示名称

应该list插件的问题?

**Comment by bihell** [comment]
嗯组件的问题，等有时间了处理下。

**Comment by xiaoboisbest** [comment]
BasicTree的属性【replaceFields】已经过期，需要更换成【fieldNames】
另外新增属性 style="width: 350px"。就能正常显示了。

另外部门的显示，TreeSelect 组件中，fieldNames里貌似没有title属性，需要改为label才能正常显示。

**Comment by bihell** [comment]
处理掉了
