### ISSUE TITLE
dice-server访问api时报错

### ISSUE THREAD

**Issue by jinzhi0123** [bihell/Dice#182]
## Question（提问）

运行dice-server访问api时报错，无代码改动。
本人不是java选手，感谢您的帮助。

#### Steps to reproduce（问题复现步骤）

1. 正常填写mysql和redis地址，执行init的SQL文件后运行
2. dice-font/通过swagger访问api（以/blog/nuxt/option为例）时报错

#### Screenshot or Gif（截图或动态图）

![image](https://github.com/bihell/Dice/assets/88891480/1ba4107b-f6aa-4fa6-a4d1-5759b608d57d)
![image](https://github.com/bihell/Dice/assets/88891480/473335ed-df4b-4970-b546-a0d44a856eba)
![image](https://github.com/bihell/Dice/assets/88891480/44d60845-c00d-47b1-a159-cb222f79d57f)
配置：
![image](https://github.com/bihell/Dice/assets/88891480/46a5538f-429d-408e-843c-1fc54359951c)

#### Other relevant information（格外信息）
- Your OS: Windows 11
- Node.js version: 20.11
- Mysql Version: 8.0

**Comment by jinzhi0123** [comment]
复现步骤似乎没有正常显示出来
1. 正常填写mysql和redis地址，执行init的SQL文件后运行
2. dice-front访问/swagger访问API（以/blog/nuxt/option为例）后报错

**Comment by bihell** [comment]
该错误请无视，只是日志记录错误，因为 Blog 这块 API 是之前古早做的，所以一直没时间去维护。本身功能无异常，等以后有时间统一处理。
