### ISSUE TITLE
想询问一下登录方面的问题（不用mock，自己搭建的后台服务）

### ISSUE THREAD

**Issue by Noedge55** [bihell/Dice#37]
现在存在的问题是，登录之后，后台返回20000，登录成功，界面不反应不跳转，而且路由也没有变化感觉没有走router.beforeEach钩子 ，也没有报错
这是什么因呢

**Comment by bihell** [comment]
如果你前端直接拷贝的我的 建议你一步步调试下这个 js https://github.com/bihell/Dice/blob/master/dice-admin/src/permission.js    如果登录成功是 login 页面跳转的 查看 Dice/dice-admin/src/views/login/index.vue 里面的 handleLogin
